sudo: false
branches:
  only:
  - source
language: ruby
rvm:
- 2.2.7
before_script:
- git config --global user.name "Miguel Angel Quinones"
- git config --global user.email "miguel@miqu.me"
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- rake setup_github_pages[$REPO_URL]
script:
- rake generate
after_script:
- rake deploy
env:
  global:
  - GH_REPO="DarthMike/darthmike.github.io"
  - secure: HjpJrszAByX3gw56FWt090RWH6pDBdoQp6yGgEIPeqDHUr+H338orzcz3MBNvuqecbDO1VsNAUIUSwOCrf6f6fXfwgzX7UTVRUpUuRwVrwrNnO+5seudgrUI952wvrXqMIUlM5e6bthobv1w9oS2z2YipNB4eKMAl4aKtkW6Fjo=
